import Navbar from '../Components/Navbar';
import Footer from '../Components/Footer';
import '../Assets/privacy.css';
import { TabTitle } from '../utils/Functions';

function Privacy() {
  TabTitle('Privacy policy - Hospyta');
  return (
    <div className="Privacy">
      <Navbar/>
      <div id='contents'>
        <h1>PRIVACY POLICY - HOSPYTA</h1>
        <h2>BEFORE YOU DIVE IN</h2>
        <p>Thank you for joining us at Hospyta Healthcare Limited. While you are here, it's worth knowing that your right to privacy is a concern. We respect the privacy rights of our online visitors and recognize the importance of protecting the information collected from them.</p>
        <p>This Privacy Policy will apply to the website that you are visiting, www.hospyta.com (the "Website"); the Hospyta Mobile Application, (the "Hopyta Mobile") which are owned by Hospyta Healthcare Limited (the "Company" "Us"). The purpose of this Privacy Policy is to inform you of what kinds of information we collect from 'You" our user/visitor and our practices for using, maintaining, sharing, and protecting that information in connection with our services and our products. This Privacy Policy also describes the rights and choices you may have concerning your Personal Information and how you may contact us. Please note that this policy applies only to websites and Mobile Applications owned by the Company, and not to websites maintained by other companies or organizations to which we link.</p>
        <p>This Privacy Policy is not a contract and does not create any contractual rights or obligations.</p>
        <h2>ABOUT HOSPYTA HEALTHCARE LIMITED</h2>
        <p>Hospyta Healthcare Technologies is a Health-Tech Startup with huge potential to drive innovation and adoption of digital technology in the healthcare industry. We aim to take everything that is “healthcare” online. This will make healthcare-related services and products far more conveniently accessible to the general population, including healthcare and non-healthcare participants than is presently the case. Hospyta provides an online marketplace hub that is exclusively tailored to the needs of the healthcare industry. We provide a platform that allows healthcare consumers to interact as seamlessly as possible with healthcare vendors, medical professionals, and other healthcare facilities and services.</p>
        <h2>COLLECTION OF DATA (TYPES AND HOW)</h2>
        <b>Log Files and Cookies</b>
        <p>If you visit Hospyta Website to view our services only and check around, we can only collect some of the data regarding your activities with our cookies and save your log files. (Check cookie Privacy please). Our servers automatically record information that your browser or application sends as Log Data. This Log Data may include information such as your IP address, browser type or the domain from which you are visiting, the websites you visit, the search terms you use, and any advertisements on which you click.  We use Log Data to monitor the website’s use and our Service and the Website's technical administration. We do not associate your IP address with any other personally identifiable information to identify you personally.</p>
        <p>We use cookies as a technology to passively collect demographic information, and personalize your experience on our site and other activities. Cookies are small files downloaded to your computer via your browser to track activities within websites. Cookies can be linked to information regarding pages you viewed and preferences on these pages. This information is used to deliver optimal services to you. Also, we use cookies to deliver content specific to your interest and location and to monitor Website usage.  Most browsers are automatically set to accept cookies whenever you visit a website. You can disable cookies or set your browser to alert you when cookies are being sent. However, some areas of our sites will not function properly if you do so. Please note that this privacy policy does not cover the use of cookies by any advertisers.</p>
        <b>Personal Information</b>
        <p>If you desire to join Hospyta i.e to sign-up/opt-in and leverage one of our various products and services; we may need to collect additional information from you. The sole aim of collecting your information most especially your personal data and demographics is to provide you with the products and services made available through our Website and Mobile Apps, including, to know you better and communicate with you, and manage your registered user account, if you have one. Personally identifiable information that we may collect in the first place may include your full name, username, password, email address, address, telephone number, birth date, gender volunteered health information and other information that you decide to provide us with, or that you decide to include in your profile. We may also need to collect additional information based on the service you are applying for; e.g for Telemedicine Service you may need to provide us with your symptoms, medical history and surgical history, and also your allergies if you have one; and other medical-related information based on demand. These data are called Protected health information. (See more information below)</p>
        <h2>USE OF DATA</h2>
        <p>We respect your privacy and will not use your information or provide it to any third party for marketing purposes. We may collect data regarding your activities on our Website or Mobile App so as to tailor our services unique to you. For example (Tracking and reminding you of your medication, Menstrual tracking for women and as well other services you may find valuable and personal. We may make some places mandatory for you to provide specific information so as to provide you with efficient service, it's up to you to opt out, but know that you will be restricted from certain services if you fail to provide some necessary information we ask for, e.g filling up a symptom checker or medical history so as to analyse your state of health. We may also use your data, especially personal information activities, to send you reminders, health tips and useful information regarding new services that you may find useful. You are in total control of how you will receive the information we might send to you!</p>
        <p>We may also use your information for billing, such as sending you invoices and receipts for services rendered to you. We may also use your data to conduct research, respond to law enforcement and also for analytics and reporting. Again, we will make you understand every process involved in the use of your data, this is primarily in the form of giving you the control to opt-in and tips on what to expect, of which on any occasion, you can opt-out either by unsubscribing or sending us an email request.</p>
        <h2>PROTECTED HEALTH INFORMATION</h2>
        <p>This Privacy Policy Section applies to Health information collected from users who register and log in ("Members") to the password-protected and secure portions of our sites ("Secure Platforms"). The Secure Platforms allow eligible Members to use Hospyta Services Most, especially the Telemedicine Service and provide us with information such as Symptoms, Medical and Surgical histories and other medical information we may need to tailor our services to you. All information collected and stored by Hospyta or added by our Members into such Secure Platforms is considered Protected Health Information ("PHI") and/or medical information and is governed by laws that apply to that information. How Hospyta uses and discloses such PHI is in accordance with the applicable Notice of Privacy Practices. Hospyta aims to save that PHI in a Decentralised manner. Meaning your "Data is in Your Hand" and you have absolute control of how and when to use your PHI. Hopyta Healthcare Limited will not use or disclose PHI for advertising, marketing, or other use-based data mining purposes and will not combine it with other data such as cookies or third-party and will not sell it.</p>
        <h2>SHARING INFORMATION (THIRD PARTY)</h2>
        <p>We engage certain trusted third parties to perform functions and provide services to us, including, without limitation, hosting and maintenance, customer relationship, database storage and management, and payment processing and management systems, public or private entities to which we are obliged to provide your data in order to comply with any law Tax Agency. We will share your personally identifiable information with these third parties, but only to the extent necessary to perform these functions and provide such services, and only pursuant to binding contractual obligations requiring such third parties to maintain the privacy and security of your data. Our Websites may contain links to other online platforms operated by third parties. We do not control such other online platforms and are not responsible for their content, their privacy policies, or their use of your information. Information you provide on public or semi-public venues, including information you share on third-party social networking platforms (such as Facebook, LinkedIn or Twitter) may also be viewable by other users of the Websites and/or users of those third-party online platforms without limitation as to its use by us or by a third party. Our inclusion of such links does not, by itself, imply any endorsement of the content on such platforms or of their owners or operators except as disclosed on the Websites. We expressly disclaim any and all liability for the actions of third parties, including but without limitation to actions relating to the use and/or disclosure of Personal Information by third parties. Any information submitted by you directly to these third parties is subject to that third party's privacy policy.</p>
        <h2>INTERNATIONAL TRANSFERS</h2>
        <p>Due to service efficiency, it is necessary that we give access to your personal data to authorized personnel of our entity as well as to third parties that support us in the services we offer you, namely: Financial entities, Providers of storage of data, Healthcare Technology associates involved in interoperability and connected healthcare. Some of the above-mentioned service providers are located in territories outside Nigeria. In such cases, we inform you that we transfer your data with appropriate safeguards and always keep your data secure.</p>
        <h2>YOUR CHOICES AND CONTROL</h2>
        <p>If you use any of our services, you are responsible for maintaining the confidentiality of your account at your end and passwords and for restricting access to your computer, and unauthorised access to your PHI; and you agree to accept responsibility for all activities that occur under your account or password. The company reserves the right to refuse service, terminate accounts or cancel orders at its sole discretion.</p>
        <p>In particular, regardless of the purpose under which we process your data; you have the right to Access, modify And download your Data and protected health information, as long as you have passed the necessary verifications to make sure you are the right person accessing the information.</p>
        <h2>SECURITY AND SAVING OF DATA</h2>
        <p>We will keep your data secured and accessible as long as you are a registered subscriber with us. You can have access to your data as long as you want; we may need some security verifications to make sure you are the person accessing your Protected health information. This can come in the form of Identity verification, KYC and other security measures.</p>
        <p>We may also require routine security checks so as to make sure you are in keeping with your data.</p>
        <p>If you have given us your consent to process your data for any purpose, you also have the right to withdraw your consent at any time. Some of the ways in which you can withdraw your consent are explained in the section in which we explain the purposes for which we process your data.</p>
        <p>Because we maintain our PLATFORMS to protect your data from accidental or malicious loss and destruction, residual copies of your personal and protected health information may be retained in our backup and archival systems for a limited period of time, after which the information will be automatically deleted or put beyond use where deletion is impossible.</p>
        <h2>CHANGES TO THIS PRIVACY POLICY</h2>
        <p>We may change the information contained in this Privacy Policy from time to time. If we do so, we will notify you by various means through the Platform *for example, through a banner, pop-up or push notifications, or even communicate to your email address when the change in question is significant to you or patterning.</p>
        <h2>QUESTIONS AND COMMENTS</h2>
        <p>If you have any questions or clarifications regarding our Privacy policies and use of your data, kindly send us an email. <a id="mailid" href="mailto:qa@hospyta.com">qa@hospyta.com</a>.</p>
      </div>
      <Footer/>
    </div>
  );
}

export default Privacy;