import Navbar from '../Components/Navbar';
import Footer from '../Components/Footer';
import '../Assets/Terms.css';
import { TabTitle } from '../utils/Functions';

function Terms() {
  TabTitle('Terms of use - Hospyta');
  return (
    <div className="Terms">
      <Navbar/>
      <div id="contents">
        <h1>TERMS OF USE AND CONDITIONS</h1>
        <p>These Terms of Service and Conditions will apply to the use of our website, www.hospyta.com (the "Website"); the Hospyta Mobile Application, (the "Hopyta Mobile" "App&") which are owned by Hospyta Healthcare Limited (the "Company" "Us").<br/>These Terms of use describe some obligations binding the Company and the user/visitor  (“you”,“your” or“Client”), who signed up and/or visited the Companies platforms. <br/>Please also review our Privacy Policy, which explains how our Services treat your personal data and protect your privacy when you use our Services. By accessing our Services, you are agreeing to these Terms and our Privacy Policy.</p>
        <p>Hospyta Healthcare Limited provides a Telemedicine platform, and e-commerce platform all combined in a central Hub where participants can leverage Digital technology to fulfil Their healthcare-related needs. Hospyta Healthcare Limited facilitates your access to telemedicine, chronic condition management, and virtual expert medical services ("Hospyta Healthcare Services").
        This Disclaimer applies to visitors to our publicly available websites that are owned and operated by the Company, and their associated domains and mobile applications (collectively, the "Products"). For the purposes of this Disclaimer, "you" and "your" means you as the visitor or user of the Websites and/or apps. By using the Websites and apps, you expressly agree to the terms and conditions set out in this Disclaimer. If you do not agree to this Disclaimer, you should immediately cease all use of and access to the Websites and apps.</p>
        <h2>ACCESSING OUR SERVICES AND OUR ROLE</h2>
        <p>Hospyta provides you access to healthcare-related services ranging from Seeing Doctors online, getting a drug prescription and Medical equipment and having them delivered to you. 
        Hospyta Healthcare's role is to make certain telehealth related services available to you and/or facilitate your access to telemedicine, expert medical services, and chronic condition management services. Hospyta Healthcare is independent of healthcare providers who provide telemedicine services and is not solely responsible for such healthcare providers' acts, omissions or for any content of the communications made by them. Hospyta Healthcare does not engage in the practice of medicine. Access to our Services is administered in Nigeria ( "NG" and is intended for users in the NG and as well as other rejoins who accept our services. But you may not use our Services in any jurisdiction where offering, accessing or using our Services would be illegal or unlawful.)</p>
        <h2>FOR NON-REGISTERED USERS</h2>
        <p>We make some Services available without registering or obtaining a password. We call these "Public Available Services." This includes visiting our Website/Blog watching some video demos, and or trying out our services. You may make personal, non-commercial use of the Public Services so long as you comply with these Terms. Information on the publicly available Websites does not provide medical advice and does not create a healthcare provider/patient relationship between you and Hospyta Healthcare or otherwise. Any services provided by or content accessed from the public Websites/blog are for informational purposes only and are not intended to replace the advice of your healthcare provider. Please consult your doctor or other qualified healthcare providers if you have any questions about a medical condition. Contact appreciate bodies in terms of emergency situations.</p>
        <p>HOSPYTA IS NOT RESPONSIBLE OR LIABLE FOR ANY ADVICE, COURSE OF TREATMENT, DIAGNOSIS OR ANY OTHER INFORMATION, SERVICES OR PRODUCTS THAT YOU MAY OBTAIN THROUGH THE WEBSITES.</p>
        <h2>NATURE OF THE CONTENT APPEARING ON OUR SERVICES</h2>
        <b>REGISTERED USERS</b>
        <p>Some of our Services are protected by technical measures intended to safeguard the confidentiality, integrity and accessibility of sensitive information our users store and share using our Services. In order to obtain Credentials, you must provide certain information about yourself. If you are registering for a Protected Service, or accessing or using, or attempting to access or use, a Protected Service on behalf of, or for the benefit of, someone other than yourself such as your child, employer, client or customer (each, a "Principal") - you must also identify and provide information about each Principal. If you sign up for one of our Protected Services you may be asked to agree to a user agreement (your "User Agreement"). In such cases, you will be asked to expressly consent to your User Agreement, for example, by checking a box or clicking on a button with terms such as "I agree"  or the like. Your Credentials are unique to you. You should immediately notify us if your Credentials have been stolen or compromised. You are responsible for all activities that occur under your Credentials until you have properly notified us that your Credentials have been stolen or compromised. Further, you represent, warrant and covenant that: the information you submit in obtaining your Credentials is complete and accurate and identifies you and the name of each of your Principals; you will not share your Credentials with anyone else; you will not circumvent, or attempt to circumvent, any technical measures that we have put in place to safeguard the Protected Services; you will not, without our prior written approval, access or use, or attempt to access or use, any portion of the Protected Services other than with (i) a commercial browser (such as Chrome, Internet Explorer or Mozilla Firefox), (ii) an application made for mobile or handheld device(s) that is developed and distributed by us, or (iii) our application programming interface ("API") using Credentials issued to you directly by us, and only us; and You will not access or use, or attempt to access or use, a Protected Service without validly-issued active Credentials. We reserve the right to suspend or terminate your access to any Protected Service at any time, with or without cause or notice. We shall not be liable to you in any way if we suspend or terminate your access to a Protected Service or our Services.</p>
        <p>Our Services may include text, data, graphics, images, video or other content (collectively, "Content") created by us or third parties, including other users, professionals, partners, advertisers, sponsors, consumers and governmental agencies. The Content is provided for general informational purposes, but should not be relied upon for personal, professional, medical or regulatory decisions.</p>
        <h2>YOUR OBLIGATIONS</h2>
        <b>Copyright</b>
        <p>All content provided on this Website is the copyright of the Company or its content suppliers. It is prohibited to copy, reproduce, modify, display, republish, upload, post, transmit, distribute, alter, prepare any derivative works of, or otherwise use any material from this Website without the prior express written consent of Hospyta Healthcare Limited.</p>
        <b>User Obligations</b>
        <p>By using Our Services, you agree to comply with all laws applicable to your use of the Websites and App, you will not interfere with a third party's use and enjoyment of the Services, and you will not interfere with or disrupt Hospyta Healthcare’s or its vendors' security measures. You agree not to: Send or otherwise transmit to or through the Websites and App any unlawful, infringing, harmful, harassing, defamatory, threatening,
        hateful or otherwise objectionable material of any kind, any material that can cause harm or delay to the Products/Services or computers of any kind, and any unsolicited advertising, solicitation or promotional materials; Restrict or inhibit any person from using our services; Reverse engineer, disassemble or decompile any section or technology on the Websites and App , or attempt to do any of the foregoing; Gain unauthorized access to the Websites and App, to other users' accounts, names, personally identifiable information or other information, or to other computers or websites connected or linked to the Websites; Launch or use any automated system, including without limitation, "robots," "spiders," or "offline readers," that access the Websites and App in a manner that sends more request messages to our servers in a given period of time than a human can reasonably produce in the same period by using a conventional web browser; Post, transmit or otherwise make available any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment; Alter or modify any part of the content or services offered on or through the Websites; Purposefully misrepresent your identity or affiliation; Collect any information from the Websites for any purpose other than individual personal use; Attempt, assist or permit any persons in engaging in any of the activities described above.</p>
        <h2>YOUR INTERACTIONS AND COMMUNICATIONS WITH US AND OUR SERVICES</h2>
        <p>We are obliged to protect the confidentiality, integrity and availability of the information housed and shared on our Services, as well as the stability of our Services, and you agree to the following safeguards. Accordingly, you agree that you will not, nor will you attempt to: disassemble, decompile or reverse engineer our Services; harvest, retrieve, index or publish any portion of our Services unless you are a Public Search Engine engaging in Public Search Services; disable or circumvent our usage safeguards, including safeguards designed to regulate the nature or amount of data
        you are permitted to extract from our Services or the frequency of which you may access such data, or make calls to our API other than those authorized in our API documentation; ]remove any copyright, trademark or other proprietary rights notices contained in or on our Services; or engage in any activity other than those expressly permitted in these Terms and your User Agreement(s).engage in any activity other than those expressly permitted in these Terms and your User Agreement(s).</p>
        <p>When you sign-up for or log in to one of our Protected Services, or when you submit information on a web form or email or instant message us, you are communicating with us electronically. When you visit our websites, we and certain third-party service providers collect information during your visit. In each case, the nature of the information we collect, the duration and manner of how we retain it, how we use it, and to whom we disclose it, is governed by our Privacy Policy.
        As part of providing our Services to you, we may need to provide you with certain communications, such as service announcements and administrative messages. Such communication may be by email, instant message, short message service, a posting on our Services or some other mechanism. You consent to receive such communications from us electronically. If you have registered for one or more of the Protected Services, our Service announcements and administrative messages we provide you are considered part of the Protected Services themselves, which you may not be able to opt-out from receiving until you cease using, or deactivate your Credentials to, such Protected Services. You agree that all agreements, notices, authorizations, disclosures and other communications that we provide to you electronically, as well as any acceptances, agreements, consents or authorizations that you provide to us electronically, satisfy any and all legal requirement(s) that such communications be in writing.</p>
        <p>You retain ownership of the intellectual property rights you hold in the Content you submit to our Services. When you submit Content on our Services, you grant us and those we work with a worldwide, royalty-free right to store, publish, publicly perform, display, use and distribute such Content as further described in our Privacy Policy and, if applicable, in your User Agreement. 
        For some of our Services, your User Agreement or settings may narrow the scope of our use of the Content you submit. You can find more information about how we use and store Content in our Privacy Policy or, if applicable, in your User Agreement.
        If you submit to us any ideas, suggestions or proposals (collectively, "Suggestions") relating to our Services or other products or services by any means - such as through "Contact Us," by email or other communication channels, one of our communities or user forums, or to our customer support or other personnel - such Suggestions (1) are not governed by our Privacy Policy, (2) we are under no obligation of confidentiality, express or implied, with respect to such Suggestions; (3) we are entitled to use or disclose (or choose not to use or disclose) such Suggestions in any way and for any purpose; (4) such Suggestions automatically become our property without any obligation; and (5) you are not entitled to any accounting, compensation or reimbursement of any kind from us under any circumstances except otherwise specified prior to your submission.</p>
        <p>Except for your Content, as between you and us, all right, title and interest in and to our Services, the Content, and the structure, organization and arrangement thereof, are and remain the exclusive property of us and our licensors.
        Except for the limited specific rights we grant you above, you may not reproduce, modify or prepare derivative works based upon, distribute, sell, transfer, publicly display, publicly perform, exploit or otherwise use our Services or any Content.</p>
        <h2>MODIFICATIONS TO THESE TERMS OF USE</h2>
        <p>Hospyta may, at any time and from time to time, amend this Disclaimer. Any changes will be effective immediately upon posting. You agree to review the Disclaimer periodically and your use of the Websites following any such change constitutes your agreement to follow and be bound by this Disclaimer as amended.</p>
        <h2>MISCELLANEOUS</h2>
        <p>If you are accepting these Terms on behalf of your employer or another entity, you represent and warrant that (i) you have the full legal authority to bind your employer or such legal entity
        to these Terms, (ii) you have read and understand these Terms, and (iii) you agree, on behalf of the Client, to these Terms.</p>
      </div>
      <Footer/>
    </div>
  );
}

export default Terms;